### ISSUE TITLE
Add an option to extract the bodies of the external definitions

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#114]
For now, whenever possible we treat foreign definitions as opaque, that is we treat all external functions as opaque and thus don't look at their bodies, treat external structures without public fields as opaque, etc. It is sometimes useful to extract the bodies of the external definitions, and Eurydice needs this: we need to add a CLI option for this. Also, it might be good to be able to tweak this behavior, for instance by extracting only the bodies of the functions marked as `#[inline]`, etc.

**Comment by Nadrieril** [comment]
Ok, so foreign functions/methods, structs that have private fields, anything else?

**Comment by Nadrieril** [comment]
This is harder than expected, because the only MIR we can access for foreign functions is optimized MIR which we don't support well
