### ISSUE TITLE
Detect overflow checks properly

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/charon#125]
After https://github.com/AeneasVerif/charon/pull/124, there's still a case where we don't detect overflow checks properly:
```rust
fn div_signed_with_constant() -> i32 {
    const FOO: i32 = 42;
    FOO / 2
}
```
gives:
```
fn test_crate::div_signed_with_constant() -> i32
{
    let @0: i32; // return
    let @1: bool; // anonymous local
    let @2: bool; // anonymous local
    let @3: i32; // anonymous local
    let @4: i32; // anonymous local

    @1 := const (2 : i32) == const (-1 : i32)
    @3 := test_crate::div_signed_with_constant::FOO
    @2 := move (@3) == const (-2147483648 : i32)
    @4 := test_crate::div_signed_with_constant::FOO
    @0 := move (@4) / const (2 : i32)
    return
}
```
because the constants are inserted in the middle of the checks.

**Comment by sonmarcho** [comment]
Actually, there is a way to fix that I think: we simply need to swap the order of the micro-pass which simplify the constants (by inserting intermediate let-bindings) and the micro pass which removes the dynamic checks. One issue is that one of the two operates on ULLBC and the other on LLBC... But it should be easy to update one of the two to work on the proper AST (I guess the constant simplification can be easily moved).

**Comment by Nadrieril** [comment]
Oh! I assumed it was rustc's fault. Yeah sounds good
