### ISSUE TITLE
Allow selecting packages within workspaces

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#126]
Currently Charon appears to parse the entire workspace instead of the package in the current directory.

When executing `charon` in a member of a workspace I'd expect it to operate only on this crate. hax allows specifying packages and only uses the current crate.

**Comment by Nadrieril** [comment]
Noting here for future reference: @W95Psp says to look at the `CARGO_PRIMARY_PACKAGE` variable
