### ISSUE TITLE
`cargo-charon` fails to parse arguments correctly

### ISSUE THREAD

**Issue by ivanbakel** [AeneasVerif/charon#19]
**Cargo version**: `cargo 1.66.0-nightly (7e484fc1a 2022-10-27)`

I installed `cargo-charon` as a Cargo CLI extension using `cargo install`. Invoking `cargo charon` fails for me on a simple repository due to what appears to be an argument-parsing error:

```
error: Found argument 'charon' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-charon [FLAGS] [OPTIONS]

For more information try --help
```

Manually running the `cargo-charon` executable from where Cargo installed it to works as expected.

---

I took the above approach because the executable is named like a Cargo plugin, and because the documentation suggests something which no longer works (`cargo run` errors out due to the lack of a default executable.) If `cargo-charon` isn't meant to be installed like this, I'm happy to update the docs in some way.

**Comment by sonmarcho** [comment]
I'm really sorry for my late answer: for some reason I didn't receive a notification for your issue. I updated the README in a recent PR: could you confirm that the new explanations work for you? Also note that I changed the name `cargo-charon` to `charon` as it was indeed confusing.

**Comment by ivanbakel** [comment]
Looks good! I think that this is a non-issue with a renamed executable, since it doesn't look like a cargo plugin.
