### ISSUE TITLE
Handle build.rs

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#190]
Charon can't handle crates with a `build.rs` right now. It generates a `build_script_build.llbc` instead and then fails with

```
error: failed to run custom build command for `charon-build-rs v0.1.0`

Caused by:
  could not execute process `target/debug/build/charon-build-rs-28ab3466db3344d5/build-script-build` (never executed)

Caused by:
  No such file or directory (os error 2)
```

To reproduce create a new crate and give it a `build.rs` file. It only needs an empty `main` function.

**Comment by Nadrieril** [comment]
@W95Psp how do you handle the case of `build.rs` in a project?

**Comment by W95Psp** [comment]
hax skips crates that are build scripts (looking at their name, which is not super nice):
https://github.com/hacspec/hax/blob/455fbeb20070c0dc7a79b0499bf24b765f5b4110/cli/driver/src/driver.rs#L121

**Comment by W95Psp** [comment]
Interesting! Yeah, in hax, I try to never pass arguments to cargo myself, so that the user can specify whatever arguments to `cargo`, including a specific target

A super reliable way to do that would be to use `cargo metadata` or `cargo build --build-plan`

**Comment by zhassan-aws** [comment]
In Kani, we use [`host-config`](https://doc.rust-lang.org/cargo/reference/unstable.html#host-config) to only run the Kani compiler for non-build scripts, and run rustc otherwise.

See https://github.com/model-checking/kani/blob/5dc5e0bf25572d93917c43d00e94a022b3557b9d/kani-driver/src/call_cargo.rs#L274
