### ISSUE TITLE
Ignore dev-dependencies

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#2]
Charon appears to expect dev-dependencies to be compiled, i.e. running `cargo build` is not enough.
If this is intentional, the recommendation should be changed to run `cargo build --tests` or a switch could be added to not look at tests.

**Comment by Kachoc** [comment]
Thanks for this useful remark! According to what you write, I understand you tested with `cargo build --tests` and it worked? Which dependencies were concerned by this?

**Comment by franziskuskiefer** [comment]
Yes, building with tests solves the issue somewhat (see my comment in #3).

> Which dependencies were concerned by this?

Charon appears to expect all dependencies (`dependencies` and `dev-dependencies`, I didn't test others) to be built.

**Comment by sonmarcho** [comment]
Charon now works with `cargo` so I'm closing this issue which is obsolete.
