### ISSUE TITLE
Failure when destructuring arrays

### ISSUE THREAD

**Issue by W95Psp** [AeneasVerif/charon#203]
Charon fails with the error `Unexpected ProjectionElem::Subslice` on each function of the following code snippet:

```rust
fn f(x: [(); 1]) {
    let [_named] = x;
}

fn g(x: &[(); 1]) {
    let [_named] = x;
}

fn h(x: [(); 1]) {
    match x {
        [_named] => (),
    }
}

fn i(x: &[()]) {
    match x {
        [_named] => (),
        _ => (),
    }
}
```

Note that the failure is present only when a binding is introduced, e.g. the following doesn't fail:
```rust
fn f(x: [(); 1]) {
    let [_] = x;
}
```

**Comment by W95Psp** [comment]
I looked a bit into this, it looks pretty easy to fix: we need to handle (at least) the case `hax::ProjectionElem::ConstantIndex {offset, min_length: _, from_end: false}`.

We'd need to transform the integer `offet` into an literal expression of type usize, and then craft a `ProjectionElem::Index(v, ty_usize)`.

The part I don't get is how to produce a `v` from a literal. From what I understand, the translation context hold a set of locals. But that context seems to hold only variable identifiers along with type information, but no actual value.

**Comment by Nadrieril** [comment]
You'll have to assign the value to the constant value you want, with an `Assign` statement

**Comment by msprotz** [comment]
Can we merge branch fix-203? There's a fix for this already, correct?
