### ISSUE TITLE
Automatically generate json parsing

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/charon#215]
It's tedious to write them by hand. I found https://github.com/serde-ml/serde but it requires ocaml `>= 5.1.1`. We could write our own generator from rust possibly.

**Comment by sonmarcho** [comment]
Does it print nice error messages when it fails?

**Comment by Nadrieril** [comment]
I don't know I couldn't try because of ocaml version mismatches

**Comment by Nadrieril** [comment]
First big chunk was done here: https://github.com/AeneasVerif/charon/pull/283

**Comment by Nadrieril** [comment]
This is now done
