### ISSUE TITLE
Remove excessive type genericity

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/charon#217]
I propose that instead of using type generics (gast, `GExprBody`, etc) to reuse code between ullbc and llbc, we replace `GExprBody` with:
```rust
enum BodyKind {
  Unstructured(Vector<BlockId, ullbc_ast::BlockData>),
  Structured(llbc_ast::Statement),
}
pub struct ExprBody {
    pub span: Span,
    // etc
    pub body: BodyKind,
}
```
Then ullbc->llbc conversion changes the enum variant from `Unstructured` to `Structured` and we can remove a ton of generic types. This has the additional benefit that if we accidentally run a pass on ullbc _after_ control flow restructuring we get a panic instead of silently modifying bodies we don't care about anymore.

**Comment by sonmarcho** [comment]
This looks good to me, under the condition Charon-ML remains unchanged (as discussed).
