### ISSUE TITLE
Rename `ItemMeta`

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#241]
`ItemMeta` is now used for fields and not only items anymore, so we should rename it

**Comment by Nadrieril** [comment]
What do we want it on? Items, fields, variants, anything else? I think we should keep a `ItemMeta` that stores things like `is_opaque` and `is_local`, and make a new thing that can store `visibility` and `attributes`.

**Comment by sonmarcho** [comment]
Yes, that's basically it.
