### ISSUE TITLE
Fix match control-flow of or-patterns

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/charon#273]
The latest rustc update (https://github.com/AeneasVerif/charon/pull/272) regressed the MIR of or-patterns. When the fix (https://github.com/rust-lang/rust/pull/127028) lands, we should update our rustc version.

**Comment by sonmarcho** [comment]
I think we're done with this right?

**Comment by Nadrieril** [comment]
We haven't updated our rustc version yet, I wanted to do that this week
