### ISSUE TITLE
Fix the bare-discriminant-read example

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#278]
@Nadrieril

**Comment by Nadrieril** [comment]
This refers to [this surprising change](https://github.com/AeneasVerif/charon/pull/272/files/0fb1b5de2ba2d3fc53feb152c6469df9a4c5eb74#diff-65de021b714c84083be304ab2d85bed8012f36a79321a993007d0083e27b8201).

**Comment by Nadrieril** [comment]
More specifically, that changes indicates that the file no longer tests the codepath in charon that we wanted to test. We could use `core::intrinsics::discriminant_value` to guarantee we get the right MIR operation.
