### ISSUE TITLE
Dependency lookup is broken

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#3]
It looks like the dependency lookup isn't implementing the `-`/`_` replacement in crate names and thus can't find dependencies with a `-` in the name.

https://github.com/Kachoc/charon/blob/7154478ad283b2a8b5fc4a409187c86137505223/charon/src/main.rs#L464

**Comment by Kachoc** [comment]
Thanks for reporting this! I just pushed a commit which should fix this issue. Do you confirm it is the case?

**Comment by franziskuskiefer** [comment]
The name fixup works. But now `insert_if_not_present` always fails. I'm not entirely sure why, but building with tests causes some dependencies to be built twice with different ids/digests (maybe because of test dependent features?). And because of #2 building with tests is necessary 😬

**Comment by sonmarcho** [comment]
This issue is obsolete: now `charon` uses `cargo` to handle the dependencies properly.
