### ISSUE TITLE
Support for for-loops

### ISSUE THREAD

**Issue by msprotz** [AeneasVerif/charon#32]
Ended up hitting this code today:

```
  for j in 0..256 {
    r[j] = fqmul(r[j], F);
  }
```

This is not currently supported because it relies on an iterator trait, and we don't support traits. Rather than do a lot of peephole optimizations in Charon to recognize this and extract it as a dedicated AST for node, we suggest:
- supporting traits, in general
- adding an optional phase in charon-ml that takes care of pattern-matching on this particular usage of traits and rewriting it into a dedicated high-level For AST node

**Comment by sonmarcho** [comment]
Fixed by https://github.com/AeneasVerif/charon/pull/48
