### ISSUE TITLE
Represent data type constructors with strings instead of variant ids

### ISSUE THREAD

**Issue by msprotz** [AeneasVerif/charon#34]
A note about this piece of code: https://github.com/AeneasVerif/charon/blob/99e30132339dea5575b671cee2d15aa8458c3c03/charon/src/translate_functions_to_ullbc.rs#L1308-L1366

Right now, there are two code-paths for translating data types constructor applications.
- If we have access to the definition of the data type (it is "local"), then we look up the definition of the data type, then compute a *variant id*, which is essentially the index of the variant in the data type definition, and represent the constructor application as `AggregateKind::Adt` which takes a type identifier, followed by a *variant identifier*
- If we do not have access to the definition of the data type (it is not local), then it must be one of the few built-in types we know how to handle. One such type is `Option`, for which we hardwire the knowledge that the VariantId of None is 0, and that the VariantId of Some is 1. (My most recent PR adds Range as another builtin type.)

The main issue with this translation scheme is that we cannot handle non-local (a.k.a. opaque) types in a generic fashion, because we need that map from constructor to VariantId.

A possible solution (to be discussed) is to represent variants with mere names (i.e., strings), which would then allow for a single translation scheme, regardless of whether the definition is available or not.

@sonmarcho do you remember why VariantId's are important?

**Comment by Nadrieril** [comment]
`VariantId`s are important because we need them to get other information about the variant such as its discriminant value

**Comment by Nadrieril** [comment]
Do we still have these two code paths today? I'd expect we should be able to get `VariantId`s for any enum whether local or not

**Comment by sonmarcho** [comment]
I don't remember how it worked back then, but we now import the information about the external, public type definitions. If we have access to an enumeration variant in the local crate, it means the enumeration is public, so we have its information (unless there was an error). Actually, I think if the information is missing then we will fail to extract the body, or at least one micro-pass will fail somewhere.

**Comment by sonmarcho** [comment]
@protz could you confirm that the current state is fine on your side?

**Comment by msprotz** [comment]
I think it's fine now -- I don't remember any recent issues related to this. This comment refers to very ancient code. Thanks for checking in.
