### ISSUE TITLE
Consider adding version numbers in the .llbc files

### ISSUE THREAD

**Issue by msprotz** [AeneasVerif/charon#35]
Right now, charon-ml might fail to load a .llbc file because, say, charon produces a new construct, but charon-ml does not (yet) know how to read it. Or, worse, a .llbc file is stale (old), and charon-ml is recent, and the .llbc file has not been regenerated properly, which means that there is a version mismatch.

Version numbers might help providing a useful error message, and figure out the discrepancy.

**Comment by Nadrieril** [comment]
Done in https://github.com/AeneasVerif/charon/pull/164

**Comment by msprotz** [comment]
🙇
