### ISSUE TITLE
Traits breaks Charon

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/charon#4]
Using the `Debug` or `Clone` trait breaks Charon. Looking at the code that fails I expect that any trait will make Charon panic really.

```rust
pub fn trait_error(s: &[u8]) {
  let _array: [u8; 4] = s.try_into().unwrap();
}
```

produces the following error (`try_into` requires implementation of `Debug`).

```
[13:34:02 TRACE charon::generics:105] [check_generics]:
trait_name: core::fmt::Debug
thread 'rustc' panicked at 'assertion failed: trait_name.equals_ref_name(&assumed::MARKER_SIZED_NAME)', src/generics.rs:106:17
```

Similarly,

```rust
pub fn vec_error() {
  let _vec = vec![0u8; 5];
}
```

produces

```
[13:46:49 TRACE charon::generics:105] [check_generics]:
trait_name: core::clone::Clone
thread 'rustc' panicked at 'assertion failed: trait_name.equals_ref_name(&assumed::MARKER_SIZED_NAME)', src/generics.rs:106:17
```

**Comment by sonmarcho** [comment]
The `vec_error` has been fixed in https://github.com/AeneasVerif/charon/pull/48.
For `trait_error`: there is still an issue linked to lifetimes. A fix is coming soon.

**Comment by Nadrieril** [comment]
Both of these examples work today
