### ISSUE TITLE
Use feature flags to optionally make charon-lib completely independent from rustc

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#405]
As of today, charon-lib is almost independent from rustc: it still uses rustc because it preserves the original Rust spans ([here](https://github.com/AeneasVerif/charon/blob/93db0e1cdbc4f06befca95214fa7197909542fdd/charon/src/ast/meta.rs#L40)). We should use the `cfg` macro to (optionally) hide this, so that we can build projects which retrieve the (serialized) output of Charon and are completely independent of rustc.

**Comment by Nadrieril** [comment]
As discussed, the only thing this requires is a way to display error messages that point to source files withotu using rustc.

**Comment by Nadrieril** [comment]
Fixed in #408
