### ISSUE TITLE
Move constant bodies to be a FunDecl

### ISSUE THREAD

**Issue by Nadrieril** [AeneasVerif/charon#428]
In `crate_of_json` we do a little hack where we transform each global into a function declaration that contains its body and a new global type that points to that function. I think we should do this on the rust side too: a constant would not contain a body and instead would contain a `FunDeclId` of its initializer function.

**Comment by sonmarcho** [comment]
Isn't it what we actually used to do? (I agree with your proposal)

**Comment by Nadrieril** [comment]
Maybe before I was here; as far as I know we've always done like today.

**Comment by Nadrieril** [comment]
Fixed by #461
