### ISSUE TITLE
opam files in root

### ISSUE THREAD

**Issue by giltho** [AeneasVerif/charon#444]
Hello,

Opam requires the opam file to be at the root of the repository to allow installing/pinning the repo.
At the moment, to pin charon, one must clone the repo and pin it locally, it cannot be pinned from github.

Supposedly moving the dune-project file up the hierarchy should be sufficient.

**Comment by Nadrieril** [comment]
Hey! That's a good idea, I have a PR up that does that: https://github.com/AeneasVerif/charon/pull/446

**Comment by Nadrieril** [comment]
The PR is merged, could you try to see if that's enough?

**Comment by giltho** [comment]
I think you forgot to commit the newly-generated opam files 😬

**Comment by Nadrieril** [comment]
Huh, it seems I was running `dune` from the wrong directory so it didn't regenerate the files. Fixed by https://github.com/AeneasVerif/charon/pull/448.

**Comment by Nadrieril** [comment]
How about now?

**Comment by giltho** [comment]
Almost there! Looks like visitors and name_matcher_parser are missing as dependencies of Charon. There may be more, but I can't install the latter from opam:

![image](https://github.com/user-attachments/assets/b89d28da-93bf-4b26-94f6-68723fc9ca47)

After installing visitors:
![image](https://github.com/user-attachments/assets/31fdc901-ab94-4aea-bb09-f5c531b708a3)

**Comment by giltho** [comment]
Actually I didn't think enough, I just had to pin `name_matcher_parser` also
Another missing dependency: easy_logging
And after that it compiles :)

**Comment by Nadrieril** [comment]
Amazing! What should I do to register these dependencies correctly?

**Comment by giltho** [comment]
They should just be added to the dune-project file, see e.g. https://github.com/bugs-for-all/bfa-ocaml/blob/main/dune-project

And then the opam files need to be regenerated from that and committed

**Comment by Nadrieril** [comment]
Fixed by https://github.com/AeneasVerif/charon/pull/452
