### ISSUE TITLE
Crates doc on Github Pages

### ISSUE THREAD

**Issue by zjp-CN** [AeneasVerif/charon#445]
I've made charon's documentation hosted on Github Pages:

https://os-checker.github.io/charon/charon/index.html

I can open a PR for this if it's wanted. 😄

**Comment by Nadrieril** [comment]
Hi! That's really convenient, thanks for doing that! I'd absolutely appreciate a PR :)

**Comment by Nadrieril** [comment]
Do you use charon for a project?

**Comment by zjp-CN** [comment]
I haven't had a chance to write any analysis tool with charon yet.

I just read your paper, Charon an analysis franework for Rust, today. I think your work is awesome, because it saves tool author's time a lot. 🦀

I'll make the PR tomorrow.
