### ISSUE TITLE
Make the .ocamlformat files of Charon and Aeneas agree

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#470]
The .ocamlformat files in Charon-ML and Aeneas do not agree. The consequence is that when using a symlink to Charon, calling `dune fmt` in Aeneas often reformats the Charon files, leading to unexpected diffs. We should use the same options for both projects (the options to be used are probably the ones from Aeneas).

I believe this is the reason why the `template` files also regularly get reformatted when working locally.

**Comment by sonmarcho** [comment]
@Nadrieril this is really easy to fix, but I think we should coordinate to do it at a moment where we do not have PRs in preparation and which touch Charon-ML - the conflicts would be wild.

**Comment by sonmarcho** [comment]
Also, maybe there is an option to make `dune fmt` not follow the symlinks (which doesn't change the fact that we should make the .ocamlformat files agree).

**Comment by Nadrieril** [comment]
We definitely should do that. For the template files, unless we know how to tell ocamlformat to skip them, I can change them to be strings inside the rust code instead.

**Comment by sonmarcho** [comment]
That's not a bad idea. But I would like to try to keep them as .ml files, because it helps when maintaining them (for such simple reasons as highlighting, etc.).
