### ISSUE TITLE
The hide_marker_traits pass doesn't update the `FunSig.parent_params_info`

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#482]
The `hide_marker_traits` pass should update the number of parameters in `FunSig.parent_params_info`. This leads to bugs in Charon-ML when printing definitions, in particular [here](https://github.com/AeneasVerif/charon/blob/7a228fa1e2658cd4baa126d72fc1b171c5f452af/charon-ml/src/PrintTypes.ml#L413).

One side note: I'm not sure we actually want to keep the `parents_param_info`, and getting rid of it would solve the issue.

**Comment by Nadrieril** [comment]
I intend to remove `parents_param_info` as part of changing how we represent trait methods. What do you use it for?
