### ISSUE TITLE
Non-positive indexes for variants are unhandled

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/charon#92]
Consider:

```rust
enum Ordering {
    Lesser  = -1,
    Equal = 0,
    Greater = 1
}
```

(taken from https://github.com/RaitoBezarius/avl-verification/blob/main/src/main.rs)

Charon will crash because it will generate a `usize::MAX - 1 > u32::MAX` for https://github.com/RaitoBezarius/avl-verification/blob/main/src/main.rs#L29 variant in the pattern matching.

**Comment by Nadrieril** [comment]
https://github.com/RaitoBezarius/avl-verification/blob/main/src/main.rs works today as far as I can tell, has the issue been fixed?

**Comment by RaitoBezarius** [comment]
@Nadrieril Can you try https://github.com/RaitoBezarius/avl-verification/commit/d6dce7238ad59f67b6b9bad1b3e50984bb69e84e ?

**Comment by Nadrieril** [comment]
Oops that example doesn't use explicit discriminants
