### ISSUE TITLE
Add support for mutually recursive trait definitions

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/charon#94]
Mutually recursive traits happen in practice, for example [here](https://github.com/arkworks-rs/algebra/blob/bb663bc27e776af81e66c94d9016bde2dbba9968/ff/src/fields/prime.rs#L27) (mutual recursion between `PrimeField` and `Field`):
```rust
pub trait Trait1 {
    type T: Trait2;
}

pub trait Trait2: Trait1 {}
```

It would be good to handle those, or at least print a nice error message. For now, Charon panics with:
```
thread 'rustc' panicked at 'Invalid trait decl group:
tests4::Trait1
tests4::Trait2', src/reorder_decls.rs:116:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `tests4` (bin "tests4")
```

**Comment by dbsc** [comment]
Related problem: charon hangs when dealing with the following code snippet

```rust
pub trait Trait1 {
    type T: Trait2;
}

pub trait Trait2: Trait1 {
    type T: Trait3;
}

pub trait Trait3 {

}
```
